# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73f0818875df271ef586f0dc624a2abd07680315b0810dc2ecd81f73293f72f3f29e732b8bc9cd0517389e56b8ef64a647fe71e96e530571acb87e18cd0ff186

test:
  secret_key_base: 45500e3c010267481c7fca5112217d77998dcea044f2d43f8a590a858d56458ea494771449536e218282f7037789ed766ef66b098f0b42a4180629b6b4514457

staging:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

dev:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
