require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DishIngredientsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # DishIngredient. As you add validations to DishIngredient, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DishIngredientsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dish_ingredients as @dish_ingredients" do
      dish_ingredient = DishIngredient.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:dish_ingredients)).to eq([dish_ingredient])
    end
  end

  describe "GET show" do
    it "assigns the requested dish_ingredient as @dish_ingredient" do
      dish_ingredient = DishIngredient.create! valid_attributes
      get :show, {:id => dish_ingredient.to_param}, valid_session
      expect(assigns(:dish_ingredient)).to eq(dish_ingredient)
    end
  end

  describe "GET new" do
    it "assigns a new dish_ingredient as @dish_ingredient" do
      get :new, {}, valid_session
      expect(assigns(:dish_ingredient)).to be_a_new(DishIngredient)
    end
  end

  describe "GET edit" do
    it "assigns the requested dish_ingredient as @dish_ingredient" do
      dish_ingredient = DishIngredient.create! valid_attributes
      get :edit, {:id => dish_ingredient.to_param}, valid_session
      expect(assigns(:dish_ingredient)).to eq(dish_ingredient)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DishIngredient" do
        expect {
          post :create, {:dish_ingredient => valid_attributes}, valid_session
        }.to change(DishIngredient, :count).by(1)
      end

      it "assigns a newly created dish_ingredient as @dish_ingredient" do
        post :create, {:dish_ingredient => valid_attributes}, valid_session
        expect(assigns(:dish_ingredient)).to be_a(DishIngredient)
        expect(assigns(:dish_ingredient)).to be_persisted
      end

      it "redirects to the created dish_ingredient" do
        post :create, {:dish_ingredient => valid_attributes}, valid_session
        expect(response).to redirect_to(DishIngredient.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dish_ingredient as @dish_ingredient" do
        post :create, {:dish_ingredient => invalid_attributes}, valid_session
        expect(assigns(:dish_ingredient)).to be_a_new(DishIngredient)
      end

      it "re-renders the 'new' template" do
        post :create, {:dish_ingredient => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dish_ingredient" do
        dish_ingredient = DishIngredient.create! valid_attributes
        put :update, {:id => dish_ingredient.to_param, :dish_ingredient => new_attributes}, valid_session
        dish_ingredient.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested dish_ingredient as @dish_ingredient" do
        dish_ingredient = DishIngredient.create! valid_attributes
        put :update, {:id => dish_ingredient.to_param, :dish_ingredient => valid_attributes}, valid_session
        expect(assigns(:dish_ingredient)).to eq(dish_ingredient)
      end

      it "redirects to the dish_ingredient" do
        dish_ingredient = DishIngredient.create! valid_attributes
        put :update, {:id => dish_ingredient.to_param, :dish_ingredient => valid_attributes}, valid_session
        expect(response).to redirect_to(dish_ingredient)
      end
    end

    describe "with invalid params" do
      it "assigns the dish_ingredient as @dish_ingredient" do
        dish_ingredient = DishIngredient.create! valid_attributes
        put :update, {:id => dish_ingredient.to_param, :dish_ingredient => invalid_attributes}, valid_session
        expect(assigns(:dish_ingredient)).to eq(dish_ingredient)
      end

      it "re-renders the 'edit' template" do
        dish_ingredient = DishIngredient.create! valid_attributes
        put :update, {:id => dish_ingredient.to_param, :dish_ingredient => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dish_ingredient" do
      dish_ingredient = DishIngredient.create! valid_attributes
      expect {
        delete :destroy, {:id => dish_ingredient.to_param}, valid_session
      }.to change(DishIngredient, :count).by(-1)
    end

    it "redirects to the dish_ingredients list" do
      dish_ingredient = DishIngredient.create! valid_attributes
      delete :destroy, {:id => dish_ingredient.to_param}, valid_session
      expect(response).to redirect_to(dish_ingredients_url)
    end
  end

end
